name: Quarto Publish

on:
  push:
    branches: [ main ]     # change if your default branch is different
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python deps (optional)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Render site
        run: quarto render
      - name: Publish to gh-pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
