name: Deploy Jupyter Book

on:
  push:
    branches: [ main ]     # or your default branch
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book ghp-import
          # optional: if you have a requirements.txt, use that instead:
          # pip install -r requirements.txt

      - name: Build book
        run: jupyter-book build .

      - name: Publish to gh-pages
        run: ghp-import -n -p -f _build/html

